version: '3.7'

services:
  mongo:
    image: 'bitnami/mongodb:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password123
      # - MONGODB_ROOT_PASSWORD=password1234
      - MONGODB_DATABASE=routes
    ports:
      - 27017:27017
  # app:
  #   image: node
  #   build: .
  #   restart: aways
  #   environment:
  #     - DB_HOST=localhost,
  #     - DB_PORT=27017,
  #     - DB_USER=root,
  #     - DB_PASSWORD=password123,
  #     - DB_DATABASE=admin,
  #   ports:
  #     - 4545:4545