version: '3.7'

services:
  mongo:
    image: 'bitnami/mongodb:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password123
      # - MONGODB_ROOT_PASSWORD=password1234
      - MONGODB_DATABASE=routes
    ports:
      - 27017:27017
  # app:
  #   image: node
  #   build: .
  #   # restart: always
  #   network_mode: "host"
  #   environment:
  #     # - DB_HOST=192.168.0.102
  #     - DB_HOST=localhost
  #     - DB_PORT=27017
  #     - DB_USER=user
  #     - DB_PASSWORD=password123
  #     - DB_DATABASE=routes
  #     - NODE_ENV=production
  #   ports:
  #     - 3009:4545